import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');

describe('global background UI surfaces', () => {
  it('keeps titlebar drag affordance, terminal transparency, and session search shape wired', () => {
    const app = read('../App.vue');
    const titlebar = read('../components/app-shell/CustomTitlebar.vue');
    const monitorDock = read('../components/app-shell/MonitorDock.vue');
    const transferDock = read('../components/app-shell/TransferDock.vue');
    const settingsModal = read('../components/settings/SettingsModal.vue');
    const settingsMainUiPane = read('../components/settings/SettingsMainUiPane.vue');
    const terminal = read('../components/terminal/Terminal.vue');
    const toastContainer = read('../components/ui/toast/ToastContainer.vue');
    const terminalManager = read('../components/terminal/TerminalPanelManager.vue');
    const sftpManager = read('../components/sftp/SftpFileManager.vue');
    const sessionDock = read('../components/app-shell/SessionDock.vue');
    const sessionList = read('../components/session/SessionList.vue');

    assert.match(titlebar, /class="titlebar-drag-layer"[^>]*data-tauri-drag-region/);
    assert.match(titlebar, /\.dusk-titlebar\s*\{[^}]*align-items:\s*center[^}]*height:\s*62px/s);
    assert.match(titlebar, /\.titlebar-left,\s*\.titlebar-center,\s*\.titlebar-right\s*\{[^}]*transform:\s*translateY\(-10px\)/s);
    assert.match(titlebar, /closest\('button,\.tb-menu-item,\.monitor-dock,\.transfer-dock-root'\)/);
    assert.match(titlebar, /let titlebarResizeFrame = null/);
    assert.match(titlebar, /requestAnimationFrame\(\(\) => \{[\s\S]*width\.value = nextWidth/s);
    assert.match(titlebar, /import ToastContainer from '@\/components\/ui\/toast\/ToastContainer\.vue'/);
    assert.match(titlebar, /<div class="titlebar-center">\s*<ToastContainer class="titlebar-toast" \/>\s*<SessionDock \/>/);
    assert.match(titlebar, /\.titlebar-center\s*\{[^}]*display:\s*flex[^}]*gap:\s*8px/s);
    assert.doesNotMatch(app, /import ToastContainer from '@\/components\/ui\/toast\/ToastContainer\.vue'/);
    assert.doesNotMatch(app, /<ToastContainer \/>/);
    assert.match(settingsMainUiPane, /emit\('background-preview-change'\)/);
    assert.doesNotMatch(settingsMainUiPane, /const notifyBackgroundPreviewChange = \(\) => \{[^}]*props\.mainUiSettings\.background\s*=/s);
    assert.match(settingsMainUiPane, /mainUiSettings\.background\?\.blur[\s\S]*mainUiSettings\.background\?\.opacity[\s\S]*mainUiSettings\.background\?\.darkOverlay[\s\S]*mainUiSettings\.background\?\.lightOverlay/);
    assert.match(settingsModal, /new CustomEvent\('main-ui-settings-changed',\s*\{[\s\S]*detail:\s*\{[\s\S]*preview:\s*true[\s\S]*settings:/);
    assert.match(app, /class="app-shell has-floating-surfaces"/);
    assert.match(app, /\.app-shell\.has-floating-surfaces\s*\{[^}]*--terminal-surface-bg/s);
    assert.match(app, /\.app-shell\.has-floating-surfaces \.workspace-grid\s*\{[^}]*padding:\s*0 7px 7px/s);
    assert.match(app, /\.recent-sessions-tree-container\s*\{[^}]*border-radius:\s*var\(--niri-radius-lg/s);
    const duskDock = read('../components/app-shell/DuskDock.vue');
    assert.match(duskDock, /\.dusk-dock\s*\{[^}]*border-radius:\s*999px/s);
    assert.match(duskDock, /\.dusk-dock\s*\{[^}]*background:\s*color-mix\(in srgb,\s*var\(--tb-bg,\s*var\(--app-bg-dialog\)\)\s*86%,\s*transparent\)/s);
    assert.match(duskDock, /\.dusk-dock--compact\s*\{[^}]*border-radius:\s*999px/s);
    assert.doesNotMatch(monitorDock, /\.monitor-dock\s*\{[^}]*background:/s);
    assert.doesNotMatch(monitorDock, /\.monitor-dock\s*\{[^}]*border-color:/s);
    assert.match(monitorDock, /import\s*\{\s*ArrowDown,\s*ArrowUp,\s*Cpu,\s*HardDrive,\s*MemoryStick\s*\}\s*from\s*'@lucide\/vue'/);
    assert.match(monitorDock, /<Cpu\s+:size="12"/);
    assert.match(monitorDock, /<MemoryStick\s+:size="12"/);
    assert.match(monitorDock, /<HardDrive\s+:size="12"/);
    assert.match(monitorDock, /<ArrowUp\s+:size="12"/);
    assert.match(monitorDock, /<ArrowDown\s+:size="12"/);
    assert.match(monitorDock, /class="monitor-dock"[^>]*@dblclick\.stop/);
    assert.match(monitorDock, /document\.hidden/);
    assert.match(monitorDock, /document\.addEventListener\('visibilitychange', handleVisibilityChange\)/);
    assert.doesNotMatch(monitorDock, /<b>CPU<\/b>|内存|磁盘/);
    assert.match(transferDock, /<Teleport to="body">/);
    assert.match(transferDock, /class="transfer-dock-root"[^>]*@dblclick\.stop/);
    assert.match(transferDock, /transferCount/);
    assert.match(transferDock, /class="transfer-badge"/);
    assert.doesNotMatch(transferDock, /transferSummary|class="transfer-summary"|completed\/status\.total/);
    assert.match(transferDock, /\.transfer-popup\s*\{[^}]*position:\s*fixed[^}]*z-index:\s*99999/s);
    assert.match(transferDock, /let popupPositionFrame = null/);
    assert.match(transferDock, /window\.addEventListener\('scroll', schedulePopupPosition, true\)/);
    assert.match(sessionDock, /import\s*\{\s*ChevronLeft,\s*ChevronRight\s*\}\s*from\s*'@lucide\/vue'/);
    assert.match(sessionDock, /class="session-nav session-nav--prev"/);
    assert.match(sessionDock, /class="session-nav session-nav--next"/);
    assert.match(sessionDock, /<ChevronLeft\s+:size="13"/);
    assert.match(sessionDock, /<ChevronRight\s+:size="13"/);
    assert.match(sessionDock, /<DuskDock interactive class="session-current">/);
    assert.match(sessionDock, /class="session-state session-drag-region"/);
    assert.match(sessionDock, /class="session-identity session-drag-region"/);
    assert.match(sessionDock, /\.session-drag-region\s*\{[^}]*pointer-events:\s*none !important/s);
    assert.match(sessionDock, /const sessionIdentity = computed/);
    assert.match(sessionDock, /\{\{ sessionIdentity \}\}/);
    assert.doesNotMatch(sessionDock, /<DuskDock compact|sessionName|session-endpoint|endpoint/);
    assert.doesNotMatch(sessionDock, /session-dots|session-dot/);
    assert.match(terminal, /closest\('\.has-floating-surfaces'\)/);
    assert.match(terminal, /--terminal-surface-bg/);
    assert.match(terminal, /\.terminal-container\s*\{[^}]*padding:\s*6px 8px/s);
    assert.match(terminal, /\.terminal-container\s*\{[^}]*box-sizing:\s*border-box/s);
    assert.match(toastContainer, /class="toast-viewport"/);
    assert.doesNotMatch(toastContainer, /<Teleport to="body">|position:\s*fixed|left:\s*clamp/);
    assert.match(toastContainer, /\.toast-viewport\s*\{[^}]*position:\s*relative[^}]*max-width:\s*min\(340px,\s*28vw\)/s);
    assert.match(toastContainer, /\.toast-card\s*\{[^}]*border-radius:\s*999px[^}]*backdrop-filter:\s*blur\(12px\)/s);
    assert.match(terminalManager, /\.split-leaf\s*\{[^}]*background:\s*transparent/s);
    assert.match(app, /class="main-panel-body"[^>]*has-sftp-panel/);
    assert.match(app, /\.main-panel-body\.has-sftp-panel\s*\{[^}]*background:\s*var\(--terminal-surface-bg/s);
    assert.match(app, /\.main-panel-body\.has-sftp-panel \.terminal-panel-manager\s*\{[^}]*border-bottom-left-radius:\s*0/s);
    assert.match(app, /\.main-panel-body\.has-sftp-panel \.sftp-bottom-panel\s*\{[^}]*background:\s*var\(--terminal-surface-bg/s);
    assert.match(app, /\.app-shell\.has-floating-surfaces \.sftp-bottom-panel \.file-manager,[\s\S]*?\.app-shell\.has-floating-surfaces \.sftp-bottom-panel \.fm-table-body[\s\S]*?background:\s*var\(--terminal-surface-bg/s);
    assert.match(sftpManager, /\.file-manager\s*\{[^}]*background:\s*var\(--terminal-surface-bg/s);
    assert.match(sftpManager, /\.fm-table-body\s*\{[^}]*background:\s*var\(--terminal-surface-bg/s);
    assert.match(sftpManager, /const scheduleTransferStatus = \(\) => \{/);
    assert.match(sftpManager, /window\.removeEventListener\('sftp-clear-transfer', clearTransferHandler\)/);
    assert.match(sessionList, /class="session-search-input"/);
    assert.match(sessionList, /\.search-bar\s*\{[^}]*background:\s*transparent/s);
  });
});
