import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');

describe('global background UI surfaces', () => {
  it('keeps titlebar drag affordance, terminal transparency, and session search shape wired', () => {
    const app = read('../App.vue');
    const titlebar = read('../components/app-shell/CustomTitlebar.vue');
    const monitorDock = read('../components/app-shell/MonitorDock.vue');
    const transferDock = read('../components/app-shell/TransferDock.vue');
    const settingsModal = read('../components/settings/SettingsModal.vue');
    const settingsMainUiPane = read('../components/settings/SettingsMainUiPane.vue');
    const terminal = read('../components/terminal/Terminal.vue');
    const toastContainer = read('../components/ui/toast/ToastContainer.vue');
    const toastComposable = read('../composables/useToast.js');
    const editableSelect = read('../components/ui/select/EditableSelect.vue');
    const sessionModal = read('../components/session/SessionModal.vue');
    const tiledPanel = read('../components/terminal/TiledPanel.vue');
    const commandKnowledgePanel = read('../components/knowledge/CommandKnowledgePanel.vue');
    const terminalManager = read('../components/terminal/TerminalPanelManager.vue');
    const sftpManager = read('../components/sftp/SftpFileManager.vue');
    const sessionDock = read('../components/app-shell/SessionDock.vue');
    const sessionList = read('../components/session/SessionList.vue');
    const main = read('../main.js');
    const scrollbar = read('../styles/scrollbar.css');
    const settingsKeybindingsPane = read('../components/settings/SettingsKeybindingsPane.vue');

    assert.doesNotMatch(titlebar, /titlebar-drag-layer/);
    assert.doesNotMatch(titlebar, /<header[^>]*data-tauri-drag-region/);
    assert.match(titlebar, /\.dusk-titlebar\s*\{[^}]*align-items:\s*center[^}]*height:\s*46px/s);
    assert.doesNotMatch(titlebar, /translateY\(/);
    assert.match(titlebar, /closest\('button'\)/);
    assert.match(titlebar, /let titlebarResizeFrame = null/);
    assert.match(titlebar, /requestAnimationFrame\(\(\) => \{[\s\S]*width\.value = nextWidth/s);
    assert.doesNotMatch(titlebar, /ToastContainer|titlebar-toast/);
    assert.match(app, /import ToastContainer from '@\/components\/ui\/toast\/ToastContainer\.vue'/);
    assert.match(app, /<CustomTitlebar \/>\s*<div class="global-toast-layer"[^>]*>\s*<ToastContainer \/>/);
    assert.match(app, /\.global-toast-layer\s*\{[^}]*height:\s*21px[^}]*justify-content:\s*flex-end/s);
    assert.match(settingsMainUiPane, /emit\('background-preview-change'\)/);
    assert.doesNotMatch(settingsMainUiPane, /const notifyBackgroundPreviewChange = \(\) => \{[^}]*props\.mainUiSettings\.background\s*=/s);
    assert.match(settingsMainUiPane, /mainUiSettings\.background\?\.blur[\s\S]*mainUiSettings\.background\?\.opacity[\s\S]*mainUiSettings\.background\?\.darkOverlay[\s\S]*mainUiSettings\.background\?\.lightOverlay/);
    assert.match(settingsModal, /new CustomEvent\('main-ui-settings-changed',\s*\{[\s\S]*detail:\s*\{[\s\S]*preview:\s*true[\s\S]*settings:/);
    assert.match(app, /class="app-shell has-floating-surfaces"/);
    assert.match(app, /\.app-shell\.has-floating-surfaces\s*\{[^}]*--terminal-surface-bg/s);
    assert.match(app, /const workspaceSeparatorSize = 4/);
    assert.match(app, /const workspaceGridGap = 3/);
    assert.match(app, /\.app-shell\.has-floating-surfaces\s*\{[^}]*--workspace-side-panel-top-offset:\s*0px/s);
    assert.match(app, /\.app-shell\.has-floating-surfaces \.workspace-grid\s*\{[^}]*padding:\s*0 4px 4px/s);
    assert.match(app, /\.app-shell\.has-floating-surfaces \.workspace-panel-session,[\s\S]*?\.workspace-panel-command-knowledge\s*\{[^}]*margin-top:\s*var\(--workspace-side-panel-top-offset\)[^}]*height:\s*calc\(100% - var\(--workspace-side-panel-top-offset\)\)/s);
    assert.doesNotMatch(app, /\.workspace-panel-main :deep\(\.tiled-panel__body\)\s*\{[^}]*padding:\s*(?:[1-9]|[a-z])/s);
    assert.match(app, /\.workspace-panel-command-knowledge :deep\(\.tiled-panel__body\)\s*\{[^}]*padding:\s*0/s);
    assert.doesNotMatch(tiledPanel, /\.tiled-panel\.is-(?:padded|dense) \.tiled-panel__body\s*\{[^}]*padding:/s);
    assert.match(tiledPanel, /\.tiled-panel__body\s*\{[^}]*padding:\s*0/s);
    assert.match(commandKnowledgePanel, /\.command-knowledge-panel\s*\{[^}]*padding:\s*6px/s);
    assert.doesNotMatch(app, /\.workspace-panel-main\s*\{[^}]*align-self:\s*stretch/s);
    assert.match(app, /\.recent-sessions-tree-container\s*\{[^}]*border-radius:\s*var\(--niri-radius-lg/s);
    const duskDock = read('../components/app-shell/DuskDock.vue');
    assert.match(duskDock, /\.dusk-dock\s*\{[^}]*border-radius:\s*var\(--niri-radius-md,\s*8px\)/s);
    assert.match(duskDock, /\.dusk-dock\s*\{[^}]*height:\s*26px[^}]*background:\s*color-mix\(in srgb,\s*var\(--tb-bg,\s*var\(--app-bg-dialog\)\)\s*var\(--tb-surface-opacity,\s*98%\),\s*transparent\)/s);
    assert.match(duskDock, /\.dusk-dock--compact\s*\{[^}]*border-radius:\s*var\(--niri-radius-md,\s*8px\)/s);
    assert.match(sessionDock, /\.session-current\s*\{[^}]*width:\s*min\(320px,\s*32vw\)[^}]*gap:\s*4px/s);
    assert.match(sessionDock, /\.session-center\s*\{[^}]*flex:\s*1 1 auto[^}]*justify-content:\s*center[^}]*gap:\s*7px/s);
    assert.doesNotMatch(monitorDock, /\.monitor-dock\s*\{[^}]*background:/s);
    assert.doesNotMatch(monitorDock, /\.monitor-dock\s*\{[^}]*border-color:/s);
    assert.match(monitorDock, /import\s*\{\s*ArrowDown,\s*ArrowUp,\s*Cpu,\s*HardDrive,\s*MemoryStick\s*\}\s*from\s*'@lucide\/vue'/);
    assert.match(monitorDock, /<Cpu\s+:size="12"/);
    assert.match(monitorDock, /<MemoryStick\s+:size="12"/);
    assert.match(monitorDock, /<HardDrive\s+:size="12"/);
    assert.match(monitorDock, /<ArrowUp\s+:size="12"/);
    assert.match(monitorDock, /<ArrowDown\s+:size="12"/);
    assert.match(monitorDock, /class="monitor-dock"[^>]*@dblclick\.stop/);
    assert.match(monitorDock, /document\.hidden/);
    assert.match(monitorDock, /document\.addEventListener\('visibilitychange', handleVisibilityChange\)/);
    assert.doesNotMatch(monitorDock, /<b>CPU<\/b>|内存|磁盘/);
    assert.match(transferDock, /<Teleport to="body">/);
    assert.match(transferDock, /class="transfer-dock-root"[^>]*@dblclick\.stop/);
    assert.match(transferDock, /defineProps\(\{\s*embedded:\s*Boolean\s*\}\)/);
    assert.match(transferDock, /v-if="embedded"[^>]*class="transfer-dock transfer-dock--embedded"/);
    assert.match(titlebar, /<DuskDock class="utility-dock" interactive>\s*<TransferDock v-show="visibility\.transfer" embedded \/>\s*<button class="tb-btn" @click="toggleTheme"/);
    assert.match(transferDock, /transferCount/);
    assert.match(transferDock, /class="transfer-badge"/);
    assert.doesNotMatch(transferDock, /transferSummary|class="transfer-summary"|completed\/status\.total/);
    assert.match(transferDock, /\.transfer-popup\s*\{[^}]*position:\s*fixed[^}]*z-index:\s*99999/s);
    assert.match(transferDock, /let popupPositionFrame = null/);
    assert.match(transferDock, /useSftpTransfersStore/);
    assert.match(transferDock, /storeToRefs\(transferStore\)/);
    assert.match(transferDock, /window\.addEventListener\('scroll', schedulePopupPosition, true\)/);
    assert.match(sessionDock, /import\s*\{\s*ChevronLeft,\s*ChevronRight\s*\}\s*from\s*'@lucide\/vue'/);
    assert.match(sessionDock, /class="session-nav session-nav--prev"/);
    assert.match(sessionDock, /class="session-nav session-nav--next"/);
    assert.match(sessionDock, /<ChevronLeft\s+:size="13"/);
    assert.match(sessionDock, /<ChevronRight\s+:size="13"/);
    assert.match(sessionDock, /<DuskDock interactive class="session-current" data-tauri-drag-region>/);
    assert.match(sessionDock, /class="session-center session-drag-region" data-tauri-drag-region/);
    assert.match(sessionDock, /class="session-state"/);
    assert.match(sessionDock, /class="session-identity"/);
    assert.match(sessionDock, /const sessionIdentity = computed/);
    assert.match(sessionDock, /\{\{ sessionIdentity \}\}/);
    assert.doesNotMatch(sessionDock, /<DuskDock compact|sessionName|session-endpoint|endpoint/);
    assert.doesNotMatch(sessionDock, /session-dots|session-dot/);
    assert.match(main, /import '@xterm\/xterm\/css\/xterm\.css';\s*import '\.\/styles\/scrollbar\.css';/);
    assert.match(scrollbar, /\*::-webkit-scrollbar-button:vertical:start:decrement/);
    assert.match(scrollbar, /\.terminal-container \.xterm \.xterm-scrollable-element > \.scrollbar > \.scra\s*\{[^}]*display:\s*none !important/s);
    assert.match(scrollbar, /\.terminal-container \.xterm \.xterm-scrollable-element > \.scrollbar\.vertical > \.slider\s*\{[^}]*width:\s*var\(--terminal-scrollbar-slider-size\) !important/s);
    assert.match(sessionList, /\.session-tree-viewport::-webkit-scrollbar-button,[\s\S]*?display:\s*none !important/s);
    assert.match(settingsKeybindingsPane, /\.kb-row\s*\{[^}]*border-bottom-color:\s*color-mix\(in srgb,\s*hsl\(var\(--border\)\)\s*18%,\s*transparent\)/s);
    assert.match(terminal, /closest\('\.has-floating-surfaces'\)/);
    assert.match(terminal, /const getSubmittedCommandText = \(\) => \{/);
    assert.match(terminal, /recordCommandHistory\(getSubmittedCommandText\(\)\)/);
    assert.match(terminal, /const submittedCommand = getSubmittedCommandText\(\)/);
    assert.match(terminal, /const seedSearchTextFromSelection = \(\) => \{/);
    assert.match(terminal, /searchText\.value = selectedText/);
    assert.match(terminal, /let searchBufferVersion = 0/);
    assert.match(terminal, /searchCountCacheSignature/);
    assert.match(terminal, /markSearchBufferChanged\(\)/);
    assert.match(terminal, /case 'find': openSearch\(\); break/);
    assert.match(terminal, /openSearch\(\);/);
    assert.match(terminal, /--terminal-surface-bg/);
    assert.match(terminal, /\.terminal-container\s*\{[^}]*padding:\s*0/s);
    assert.match(terminal, /\.terminal-container\s*\{[^}]*box-sizing:\s*border-box/s);
    assert.match(terminal, /\.terminal-container\s+:deep\(\.xterm\)\s*\{[^}]*padding:\s*6px 8px/s);
    assert.match(scrollbar, /\.terminal-container \.xterm-viewport\s*\{[^}]*overflow-y:\s*hidden !important/s);
    assert.match(scrollbar, /\.terminal-container \.xterm-viewport::-webkit-scrollbar\s*\{[^}]*display:\s*none !important/s);
    assert.match(toastContainer, /class="toast-viewport"/);
    assert.doesNotMatch(toastContainer, /<Teleport to="body">|position:\s*fixed|left:\s*clamp/);
    assert.match(toastContainer, /\.toast-viewport\s*\{[^}]*position:\s*relative[^}]*flex-direction:\s*row-reverse/s);
    assert.match(toastContainer, /toast\.remove\(toasts\.value\[0\]\.id, true\)/);
    assert.match(toastContainer, /requestAnimationFrame\(async \(\) =>/);
    assert.match(toastContainer, /new ResizeObserver\(scheduleOverflowTrim\)/);
    assert.doesNotMatch(toastContainer, /toast-icon|component :is|data-slot="toast-rail"|backdrop-filter/);
    assert.match(toastContainer, /\.toast-card\s*\{[^}]*width:\s*max-content[^}]*height:\s*19px[^}]*font-size:\s*12px/s);
    assert.match(toastContainer, /\.toast-card\s*\{[^}]*border-radius:\s*var\(--niri-radius-md,\s*8px\)/s);
    assert.match(toastContainer, /\.toast-message\s*\{[^}]*overflow:\s*visible[^}]*text-overflow:\s*clip/s);
    assert.doesNotMatch(toastContainer, /text-overflow:\s*ellipsis|max-width:\s*min\(260px,\s*28vw\)|max-width:\s*180px/);
    assert.match(toastComposable, /const idToTimer = new Map\(\)/);
    assert.match(toastComposable, /removeToast\(existingId, true\)/);
    assert.match(editableSelect, /role="combobox"/);
    assert.match(editableSelect, /:aria-controls="listboxId"/);
    assert.match(editableSelect, /event\.key === 'Enter' \|\| event\.key === ' '/);
    assert.doesNotMatch(sessionModal, /label: `\$\{currentPath\}（当前配置）`/);
    assert.match(sessionModal, /let serialPortRequestId = 0/);
    assert.match(sessionModal, /requestId !== serialPortRequestId/);
    assert.match(terminalManager, /\.split-leaf\s*\{[^}]*background:\s*transparent/s);
    assert.match(app, /class="main-panel-body"[^>]*has-sftp-panel/);
    assert.match(app, /\.main-panel-body\.has-sftp-panel\s*\{[^}]*background:\s*var\(--terminal-surface-bg/s);
    assert.match(app, /\.main-panel-body\.has-sftp-panel \.terminal-panel-manager\s*\{[^}]*border-bottom-left-radius:\s*0/s);
    assert.match(app, /\.main-panel-body\.has-sftp-panel \.sftp-bottom-panel\s*\{[^}]*background:\s*var\(--terminal-surface-bg/s);
    assert.match(app, /\.app-shell\.has-floating-surfaces \.sftp-bottom-panel \.file-manager,[\s\S]*?\.app-shell\.has-floating-surfaces \.sftp-bottom-panel \.fm-table-body[\s\S]*?background:\s*var\(--terminal-surface-bg/s);
    assert.match(sftpManager, /\.file-manager\s*\{[^}]*background:\s*var\(--terminal-surface-bg/s);
    assert.match(sftpManager, /\.fm-table-body\s*\{[^}]*background:\s*var\(--terminal-surface-bg/s);
    assert.match(sftpManager, /useSftpTransfersStore/);
    assert.doesNotMatch(sftpManager, /listenEvent\('sftp-progress'|sftp-clear-transfer|sftp-transfer-status/);
    assert.match(sessionList, /class="session-search-input"/);
    assert.match(sessionList, /\.search-bar\s*\{[^}]*background:\s*transparent/s);
  });
});
